### ISSUE TITLE
Zarinpal refrenceId is wrong!!

### ISSUE THREAD

**Issue by everythinginjs** [alitnk/monopay#47]
in verifyPayment method of zarinpal in the docx. it is suggested to pass `referenceId` but when read your code figured out it must be `Authority`.

https://github.com/alitnk/monopay/blob/c0b45c40719fb7b9d2ccd169ba5fbff4445b26ec/src/drivers/zarinpal/index.ts#L44

I have had spent an hour scratching my head why my endpoint return 404.

```
import { getPaymentDriver } from "monopay";

const driver = getPaymentDriver("zarinpal", {
  merchantId: "zarinpal-merchant",
});

const receipt = await driver.verifyPayment(
  {
    amount: 5000,
    referenceId: 1234,
  },
  { ...request.query }
);
```

**Comment by Keivan-sf** [comment]
Thanks for reporting, there is indeed a problem with `referenceId` since it simply doesn't exist in zarinpal verification type

But note that authority is not passed along **options**, it's passed inas the third parameter (considered to be in `req.query` in this example which I think we could improve that  as well)

**Comment by alitnk** [comment]
Thanks @Keivan-sf!
